
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module three_bit_alu(

	//////////// CLOCK //////////
	//input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	//input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================


//Syncro'd swithez get stichez
wire [9:0]sw_d;
wire [2:0]a_w;
wire [2:0]b_w;
wire [5:0]final_w;
wire [1:0]op_code_w;

wire carry;

//=======================================================
//  Structural coding
//=======================================================

/*
alu_core my_alu(
   .a(),
	.b(),
	.op_code(),
	.rst_n(KEY[0]),
	.bbclk(),
	.op_out(),
	.carry_out(),
);
*/
de10lite fpga_interface(
	.rst_n(KEY[0]),
	.carry(carry),
	.final_in(final_w),
	.clk(MAX10_CLK1_50),
	.ctrl(SW),
	.a_out(a_w),
	.b_out(b_w),
	.op_code_out(op_code_w),
	.led(LEDR),
	.op_code_dig_one(HEX0),
	.op_code_dig_two(HEX1),
	.dig_three(HEX2),
	.dig_four(HEX3),
	.dig_five(HEX4),
	.dig_six(HEX5)
);

led_dff_sync led_sync(
   .rst_n(KEY[0]),
   .clk(MAX10_CLK1_50),
   .in_sync(SW),
   .sync_out(sw_d)
);
alu_core u_one(
	.a(a_w),
	.b(b_w),
	.op_code(op_code_w),
	.rst_n(KEY[0]),
	.bbclk(MAX10_CLK1_50),
	.op_out(final_w),
	.carry_out(carry)
);

/*


module alu_core(
   input [2:0]a,
   input [2:0]b,
   input [1:0]op_code,
   input rst_n,
   input bbclk,
   output reg [5:0]op_out,
   output reg carry_out
);
*/


endmodule
